set (LEARNTOOL_VERSION_MAJOR 1)
set (LEARNTOOL_VERSION_MINOR 1)
set (LEARNTOOL_VERSION_PATCH 0)
set (LEARNTOOL_VERSION "${LEARNTOOL_VERSION_MAJOR}.${LEARNTOOL_VERSION_MINOR}.${LEARNTOOL_VERSION_PATCH}")

